export const gamelist = [
  { name: 'Rocket League' },
  { name: "Sid Meier's Civilization V" },
  { name: 'Factorio' },
  { name: 'Grand Theft Auto IV' },
  { name: 'Grand Theft Auto V' },
  { name: 'Elite Dangerous' },
  { name: 'Kerbal Space Program' },
  { name: "PLAYERUNKNOWN'S BATTLEGROUNDS" },
  { name: "No Man's Sky" },
  { name: 'Cities: Skylines' },
  { name: 'Counter-Strike: Source' },
  { name: 'Portal 2' },
  { name: 'Banished' },
  { name: 'Arma 3' },
  { name: 'The Elder Scrolls V: Skyrim' },
  { name: 'Tomb Raider' },
  { name: 'South Park™: The Stick of Truth™' },
  { name: 'SimCity 4 Deluxe' },
  { name: 'Battlefield: Bad Company 2' },
  { name: "Sid Meier's Civilization VI" },
  { name: '3DMark' },
  { name: "Sid Meier's Civilization: Beyond Earth" },
  { name: 'Arma 2: Operation Arrowhead' },
  { name: 'Rise of the Tomb Raider' },
  { name: "Assassin's Creed IV Black Flag" },
  { name: 'Ori and the Blind Forest: Definitive Edition' },
  { name: 'Rust' },
  { name: 'Trials Fusion' },
  { name: 'The Elder Scrolls V: Skyrim Special Edition' },
  { name: 'Age of Empires II: HD Edition' },
  { name: "Mirror's Edge" },
  { name: 'Fallout 4' },
  { name: 'TrackMania United' },
  { name: 'The Long Dark' },
  { name: 'Frozen Synapse' },
  { name: 'Portal' },
  { name: 'Dota 2' },
  { name: 'The Talos Principle' },
  { name: 'Firewatch' },
  { name: 'Dead Rising 2' },
  { name: 'INSIDE' },
  { name: 'Total War: SHOGUN 2' },
  { name: 'DiRT 3' },
  { name: 'You Need A Budget 4 (YNAB)' },
  { name: 'Rise of Nations: Extended Edition' },
  { name: 'Dishonored' },
  { name: 'LIMBO' },
  { name: 'Mass Effect' },
  { name: 'Magicka' },
  { name: 'Left 4 Dead' },
  { name: 'Batman: Arkham Asylum GOTY Edition' },
  { name: 'Saints Row: The Third' },
  { name: 'Mount & Blade: Warband' },
  { name: 'Chivalry: Medieval Warfare' },
  { name: 'Stellaris' },
  { name: 'Just Cause 2: Multiplayer Mod' },
  { name: 'Tropico 4' },
  { name: 'Blackwake' },
  { name: 'Arma 2' },
  { name: 'RUNNING WITH RIFLES' },
  { name: 'Half-Life 2' },
  { name: 'Left 4 Dead 2' },
  { name: 'BRINK' },
  { name: 'Men of War' },
  { name: 'Total War: ROME II - Emperor Edition' },
  { name: 'The Stanley Parable' },
  { name: "The Beginner's Guide" },
  { name: 'Counter-Strike: Global Offensive' },
  { name: 'Max Payne 3' },
  { name: 'Lunar Flight' },
  { name: 'DiRT 3 Complete Edition' },
  { name: 'Prison Architect' },
  { name: 'GRID 2' },
  { name: 'Borderlands 2' },
  { name: 'Far Cry® 3' },
  { name: 'Universe Sandbox' },
  { name: 'The Witcher 3: Wild Hunt' },
  { name: 'XCOM: Enemy Unknown' },
  { name: 'Hitman: Absolution' },
  { name: 'Age of Empires® III: Complete Collection' },
  { name: 'PAYDAY 2' },
  { name: 'Osiris: New Dawn' },
  { name: 'DisplayFusion' },
  { name: 'Everything' },
  { name: 'Borderlands: The Pre-Sequel' },
  { name: 'Ace of Spades' },
  { name: "Brothers in Arms: Hell's Highway" },
  { name: 'BioShock' },
  { name: 'DiRT Rally' },
  { name: 'Brawlhalla' },
  { name: 'Endless Space' },
  { name: 'Screeps' },
  { name: 'Super Meat Boy' },
  { name: 'BioShock Infinite' },
  { name: 'Grand Theft Auto: Episodes from Liberty City' },
  { name: 'SUPERHOT' },
  { name: 'Poly Bridge' },
  { name: 'Deus Ex: Game of the Year Edition' },
  { name: "Tom Clancy's Splinter Cell" },
  { name: 'Burnout Paradise: The Ultimate Box' },
  { name: 'Dead Space' },
  { name: 'PAYDAY: The Heist' },
  { name: 'PROTOTYPE 2' },
  { name: 'Duskers' },
  { name: "Garry's Mod" },
  { name: 'Ultimate Epic Battle Simulator' },
  { name: 'Castle Crashers' },
  { name: 'Planetary Annihilation' },
  { name: 'The Lab' },
  { name: 'Anno 2070' },
  { name: 'Space Run' },
  { name: 'Borderlands' },
  { name: 'Cubemen' },
  { name: "Assassin's Creed" },
  { name: 'Plain Sight' },
  { name: 'Europa Universalis IV' },
  { name: 'Black Mesa' },
  { name: 'The Witness' },
  { name: 'Far Cry' },
  { name: 'Uplink' },
  { name: 'Sniper Elite V2' },
  { name: 'Lead and Gold - Gangs of the Wild West' },
  { name: 'Metro 2033' },
  { name: 'Besiege' },
  { name: 'Brothers - A Tale of Two Sons' },
  { name: 'Darwinia' },
  { name: 'GRID' },
  { name: 'Killing Floor' },
  { name: 'Antichamber' },
  { name: 'FTL: Faster Than Light' },
  { name: 'STAR WARS™: Knights of the Old Republic™' },
  { name: 'Crayon Physics Deluxe' },
  { name: 'Cities in Motion 2' },
  { name: 'Goat Simulator' },
  { name: 'Hammerwatch' },
  { name: "Sid Meier's Civilization IV" },
  { name: 'Wargame: European Escalation' },
  { name: 'Loadout' },
  { name: 'Half-Life 2: Update' },
  { name: 'Sins of a Solar Empire: Rebellion' },
  { name: "Tom Clancy's Rainbow Six 3: Gold Edition" },
  { name: 'Cities XL Platinum' },
  { name: 'Command and Conquer 3: Tiberium Wars' },
  { name: "Command and Conquer 3: Kane's Wrath" },
  { name: 'Poker Night at the Inventory' },
  { name: 'Citadels' },
  { name: 'Deus Ex: Human Revolution' },
  { name: 'Argo' },
  { name: 'Ravaged Zombie Apocalypse' },
  { name: 'RollerCoaster Tycoon 3: Platinum!' },
  { name: 'Arma 2: Private Military Company' },
  { name: 'Just Cause 2' },
  { name: 'METAL GEAR SOLID V: GROUND ZEROES' },
  { name: 'Arma 2: British Armed Forces' },
  { name: '3DMark API Overhead feature test' },
  { name: '3DMark Cloud Gate benchmark' },
  { name: '3DMark Fire Strike benchmark' },
  { name: '3DMark Ice Storm benchmark' },
  { name: '3DMark Sky Diver benchmark' },
  { name: 'Age of Empires II HD: The Forgotten' },
  { name: 'Arma 2: DayZ Mod' },
  { name: 'Arma 2: Operation Arrowhead Beta (Obsolete)' },
  { name: 'Arma 3 Apex' },
  { name: 'Arma 3 Helicopters' },
  { name: 'Arma 3 Karts' },
  { name: 'Arma 3 Malden' },
  { name: 'Arma 3 Marksmen' },
  { name: 'Arma 3 Zeus' },
  { name: 'BioShock Remastered' },
  { name: 'Borderlands DLC: Claptrap’s New Robot Revolution' },
  { name: "Borderlands DLC: Mad Moxxi's Underdome Riot" },
  { name: 'Borderlands DLC: The Secret Armory of General Knoxx' },
  { name: 'Borderlands DLC: The Zombie Island of Dr. Ned' },
  { name: 'Civilization VI - Aztec Civilization Pack' },
  { name: 'Company of Heroes' },
  { name: 'Company of Heroes (New Steam Version)' },
  { name: 'Company of Heroes: Opposing Fronts' },
  { name: 'Company of Heroes: Tales of Valor' },
  { name: 'Counter-Strike' },
  { name: 'Counter-Strike: Condition Zero' },
  { name: 'Counter-Strike: Condition Zero Deleted Scenes' },
  { name: 'Darksiders' },
  { name: 'Darksiders Warmastered Edition' },
  { name: 'Day of Defeat' },
  { name: 'Day of Defeat: Source' },
  { name: 'Dead Space 2' },
  { name: 'Deathmatch Classic' },
  { name: 'DEFCON' },
  { name: "Don't Starve Together" },
  { name: 'ED: Horizons Season Pass' },
  { name: 'Europa Universalis IV: American Dream DLC' },
  { name: 'Europa Universalis IV: Conquest of Paradise' },
  { name: 'Europa Universalis IV: Conquistadors Unit pack' },
  { name: 'Europa Universalis IV: National Monuments II' },
  { name: 'Europa Universalis IV:Native Americans Unit Pack' },
  { name: 'Europa Universalis IV: Songs of the New World' },
  { name: 'Evil Genius' },
  { name: 'Fallout: New Vegas' },
  { name: 'Far Cry 2' },
  { name: 'Far Cry 2: Fortunes Pack' },
  { name: 'Galaxy on Fire 2™ Full HD' },
  { name: 'Grand Theft Auto: San Andreas' },
  { name: 'Grand Theft Auto: San Andreas' },
  { name: 'GRID 2 GTR Racing Pack' },
  { name: 'Half-Life' },
  { name: 'Half-Life 2: Deathmatch' },
  { name: 'Half-Life 2: Episode One' },
  { name: 'Half-Life 2: Episode Two' },
  { name: 'Half-Life 2: Lost Coast' },
  { name: 'Half-Life: Blue Shift' },
  { name: 'Half-Life: Opposing Force' },
  { name: 'Half-Life: Source' },
  { name: 'Half-Life Deathmatch: Source' },
  { name: 'Hitman: Sniper Challenge' },
  { name: 'Killing Floor Mod: Defence Alliance 2' },
  { name: 'Life is Strange™' },
  { name: 'Mass Effect 2' },
  { name: 'Max Payne 3 Season Pass' },
  { name: 'Men of War: Assault Squad' },
  { name: 'Men of War: Red Tide' },
  { name: 'Mercenary Kings' },
  { name: 'Minimum' },
  { name: 'Multiwinia' },
  { name: 'Narcissu 1st & 2nd' },
  { name: 'Nation Red' },
  { name: 'Nuclear Dawn' },
  { name: 'Only If' },
  { name: 'Ori and the Blind Forest' },
  { name: 'ORION: Prelude' },
  { name: 'Path of Exile' },
  { name: 'Quake Live' },
  { name: 'Red Faction: Armageddon' },
  { name: 'Ricochet' },
  { name: 'Risk of Rain' },
  { name: "Sid Meier's Civilization IV" },
  { name: "Sid Meier's Civilization V: Brave New World" },
  { name: "Sid Meier's Civilization V: Scrambled Continents Map Pack" },
  { name: 'Sigils of Elohim' },
  { name: 'Sol Survivor' },
  { name: 'StarForge' },
  { name: 'SUPERHOT VR' },
  { name: 'Team Fortress Classic' },
  { name: 'The Elder Scrolls V: Skyrim - Dawnguard' },
  { name: 'The Elder Scrolls V: Skyrim - Dragonborn' },
  { name: 'The Elder Scrolls V: Skyrim - Hearthfire' },
  { name: 'The Witcher 2: Assassins of Kings Enhanced Edition' },
  { name: 'The Witcher 3: Wild Hunt - Expansion Pass' },
  { name: 'The Witcher 3: Wild Hunt - New Finisher Animations' },
  { name: "Tom Clancy's EndWar" },
  { name: "Tom Clancy's Rainbow Six 3: Athena Sword" },
  { name: "Tom Clancy's Rainbow Six: Lockdown" },
  { name: "Tom Clancy's Rainbow Six: Vegas" },
  { name: "Tom Clancy's Rainbow Six: Vegas 2" },
  { name: "Tom Clancy's Splinter Cell: Chaos Theory" },
  { name: "Tom Clancy's Splinter Cell: Conviction" },
  { name: "Tom Clancy's Splinter Cell: Double Agent" },
  { name: 'Torchlight II' },
  { name: 'Trine 2' },
]
